// frameworks/react/apps/table/main.tsx
import { buildData, UPDATE_SUFFIX, type Row } from '@bench/shared/data';
import { memo, useCallback, useReducer } from 'react';
import { createRoot } from 'react-dom/client';

interface State {
  readonly rows: readonly Row[];
  readonly selected: number | undefined;
}
type Action =
  | { readonly type: 'run' }
  | { readonly type: 'runLots' }
  | { readonly type: 'add' }
  | { readonly type: 'update' }
  | { readonly type: 'clear' }
  | { readonly type: 'swap' }
  | { readonly type: 'select'; readonly id: number }
  | { readonly type: 'remove'; readonly id: number };

function reducer(state: State, action: Action): State {
  switch (action.type) {
    case 'run':
      return { rows: buildData(1000), selected: undefined };
    case 'runLots':
      return { rows: buildData(10000), selected: undefined };
    case 'add':
      return { ...state, rows: [...state.rows, ...buildData(1000)] };
    case 'update':
      return {
        ...state,
        rows: state.rows.map((r, i) =>
          i % 10 === 0 ? { ...r, label: r.label + UPDATE_SUFFIX } : r,
        ),
      };
    case 'clear':
      return { rows: [], selected: undefined };
    case 'swap': {
      if (state.rows.length <= 998) return state;
      const rows = [...state.rows];
      const a = rows[1] as Row;
      rows[1] = rows[998] as Row;
      rows[998] = a;
      return { ...state, rows };
    }
    case 'select':
      return { ...state, selected: action.id };
    case 'remove':
      return { ...state, rows: state.rows.filter((r) => r.id !== action.id) };
  }
}

interface RowProps {
  readonly row: Row;
  readonly selected: boolean;
  readonly dispatch: (action: Action) => void;
}

// memo: only rows whose props change re-render (the documented way to skip work in lists).
const TableRow = memo(function TableRow({ row, selected, dispatch }: RowProps) {
  return (
    <tr className={selected ? 'danger' : ''}>
      <td className="col-id">{row.id}</td>
      <td>
        <button
          className="lbl"
          type="button"
          onClick={() => dispatch({ type: 'select', id: row.id })}
        >
          {row.label}
        </button>
      </td>
      <td>
        <button
          className="remove"
          type="button"
          onClick={() => dispatch({ type: 'remove', id: row.id })}
        >
          x
        </button>
      </td>
    </tr>
  );
});

function Table() {
  const [state, dispatch] = useReducer(reducer, { rows: [], selected: undefined });
  const send = useCallback((action: Action) => dispatch(action), []);
  return (
    <>
      <menu>
        <li>
          <button id="run" type="button" onClick={() => send({ type: 'run' })}>
            Create 1,000 rows
          </button>
        </li>
        <li>
          <button id="runlots" type="button" onClick={() => send({ type: 'runLots' })}>
            Create 10,000 rows
          </button>
        </li>
        <li>
          <button id="add" type="button" onClick={() => send({ type: 'add' })}>
            Append 1,000 rows
          </button>
        </li>
        <li>
          <button id="update" type="button" onClick={() => send({ type: 'update' })}>
            Update every 10th row
          </button>
        </li>
        <li>
          <button id="clear" type="button" onClick={() => send({ type: 'clear' })}>
            Clear
          </button>
        </li>
        <li>
          <button id="swaprows" type="button" onClick={() => send({ type: 'swap' })}>
            Swap rows
          </button>
        </li>
      </menu>
      <table>
        <tbody id="tbody">
          {state.rows.map((row) => (
            <TableRow key={row.id} row={row} selected={row.id === state.selected} dispatch={send} />
          ))}
        </tbody>
      </table>
    </>
  );
}

createRoot(document.getElementById('app') as HTMLElement).render(<Table />);

// frameworks/solid/apps/table/main.tsx
import { buildData, UPDATE_SUFFIX } from '@bench/shared/data';
import { createSelector, createSignal, For } from 'solid-js';
import { createStore } from 'solid-js/store';
import { render } from 'solid-js/web';

interface Row {
  id: number;
  label: string;
}

// A store for the rows (fine-grained label updates) and createSelector for the selection:
// the documented Solid tools for large lists.
function Table() {
  const [state, setState] = createStore<{ rows: Row[] }>({ rows: [] });
  const [selected, setSelected] = createSignal<number>();
  const isSelected = createSelector(selected);

  const run = () => {
    setState('rows', buildData(1000));
    setSelected(undefined);
  };
  const runLots = () => {
    setState('rows', buildData(10000));
    setSelected(undefined);
  };
  const add = () => setState('rows', (rs) => [...rs, ...buildData(1000)]);
  const update = () =>
    setState(
      'rows',
      (_r, i) => i % 10 === 0,
      'label',
      (l) => l + UPDATE_SUFFIX,
    );
  const clear = () => {
    setState('rows', []);
    setSelected(undefined);
  };
  const swap = () => {
    if (state.rows.length <= 998) return;
    setState('rows', (rs) => {
      const next = [...rs];
      const a = next[1] as Row;
      next[1] = next[998] as Row;
      next[998] = a;
      return next;
    });
  };
  const remove = (id: number) => setState('rows', (rs) => rs.filter((r) => r.id !== id));

  return (
    <>
      <menu>
        <li>
          <button id="run" type="button" onClick={run}>
            Create 1,000 rows
          </button>
        </li>
        <li>
          <button id="runlots" type="button" onClick={runLots}>
            Create 10,000 rows
          </button>
        </li>
        <li>
          <button id="add" type="button" onClick={add}>
            Append 1,000 rows
          </button>
        </li>
        <li>
          <button id="update" type="button" onClick={update}>
            Update every 10th row
          </button>
        </li>
        <li>
          <button id="clear" type="button" onClick={clear}>
            Clear
          </button>
        </li>
        <li>
          <button id="swaprows" type="button" onClick={swap}>
            Swap rows
          </button>
        </li>
      </menu>
      <table>
        <tbody id="tbody">
          <For each={state.rows}>
            {(row) => (
              <tr class={isSelected(row.id) ? 'danger' : ''}>
                <td class="col-id">{row.id}</td>
                <td>
                  <button class="lbl" type="button" onClick={() => setSelected(row.id)}>
                    {row.label}
                  </button>
                </td>
                <td>
                  <button class="remove" type="button" onClick={() => remove(row.id)}>
                    x
                  </button>
                </td>
              </tr>
            )}
          </For>
        </tbody>
      </table>
    </>
  );
}

render(() => <Table />, document.getElementById('app') as HTMLElement);
