// frameworks/lit/apps/table/main.ts
import { buildData, UPDATE_SUFFIX, type Row } from '@bench/shared/data';
import { html, LitElement } from 'lit';
import { repeat } from 'lit/directives/repeat.js';

class BenchTable extends LitElement {
  static override properties = {
    rows: { state: true },
    selected: { state: true },
  };
  declare rows: readonly Row[];
  declare selected: number | undefined;

  constructor() {
    super();
    this.rows = [];
    this.selected = undefined;
  }

  private run() {
    this.rows = buildData(1000);
    this.selected = undefined;
  }
  private runLots() {
    this.rows = buildData(10000);
    this.selected = undefined;
  }
  private add() {
    this.rows = [...this.rows, ...buildData(1000)];
  }
  private updateRows() {
    this.rows = this.rows.map((r, i) =>
      i % 10 === 0 ? { ...r, label: r.label + UPDATE_SUFFIX } : r,
    );
  }
  private clear() {
    this.rows = [];
    this.selected = undefined;
  }
  private swap() {
    if (this.rows.length <= 998) return;
    const next = [...this.rows];
    const a = next[1] as Row;
    next[1] = next[998] as Row;
    next[998] = a;
    this.rows = next;
  }
  private removeRow(id: number) {
    this.rows = this.rows.filter((r) => r.id !== id);
  }

  override render() {
    return html`
      <menu>
        <li><button id="run" type="button" @click=${this.run}>Create 1,000 rows</button></li>
        <li>
          <button id="runlots" type="button" @click=${this.runLots}>Create 10,000 rows</button>
        </li>
        <li><button id="add" type="button" @click=${this.add}>Append 1,000 rows</button></li>
        <li>
          <button id="update" type="button" @click=${this.updateRows}>Update every 10th row</button>
        </li>
        <li><button id="clear" type="button" @click=${this.clear}>Clear</button></li>
        <li><button id="swaprows" type="button" @click=${this.swap}>Swap rows</button></li>
      </menu>
      <table>
        <tbody id="tbody">
          ${repeat(
            this.rows,
            (row) => row.id,
            (row) => html`
              <tr class=${row.id === this.selected ? 'danger' : ''}>
                <td class="col-id">${row.id}</td>
                <td>
                  <button class="lbl" type="button" @click=${() => (this.selected = row.id)}>
                    ${row.label}
                  </button>
                </td>
                <td>
                  <button class="remove" type="button" @click=${() => this.removeRow(row.id)}>
                    x
                  </button>
                </td>
              </tr>
            `,
          )}
        </tbody>
      </table>
    `;
  }
}
customElements.define('bench-table', BenchTable);
document.getElementById('app')?.append(new BenchTable());

// frameworks/solid/apps/table/main.tsx
import { buildData, UPDATE_SUFFIX } from '@bench/shared/data';
import { createSelector, createSignal, For } from 'solid-js';
import { createStore } from 'solid-js/store';
import { render } from 'solid-js/web';

interface Row {
  id: number;
  label: string;
}

// A store for the rows (fine-grained label updates) and createSelector for the selection:
// the documented Solid tools for large lists.
function Table() {
  const [state, setState] = createStore<{ rows: Row[] }>({ rows: [] });
  const [selected, setSelected] = createSignal<number>();
  const isSelected = createSelector(selected);

  const run = () => {
    setState('rows', buildData(1000));
    setSelected(undefined);
  };
  const runLots = () => {
    setState('rows', buildData(10000));
    setSelected(undefined);
  };
  const add = () => setState('rows', (rs) => [...rs, ...buildData(1000)]);
  const update = () =>
    setState(
      'rows',
      (_r, i) => i % 10 === 0,
      'label',
      (l) => l + UPDATE_SUFFIX,
    );
  const clear = () => {
    setState('rows', []);
    setSelected(undefined);
  };
  const swap = () => {
    if (state.rows.length <= 998) return;
    setState('rows', (rs) => {
      const next = [...rs];
      const a = next[1] as Row;
      next[1] = next[998] as Row;
      next[998] = a;
      return next;
    });
  };
  const remove = (id: number) => setState('rows', (rs) => rs.filter((r) => r.id !== id));

  return (
    <>
      <menu>
        <li>
          <button id="run" type="button" onClick={run}>
            Create 1,000 rows
          </button>
        </li>
        <li>
          <button id="runlots" type="button" onClick={runLots}>
            Create 10,000 rows
          </button>
        </li>
        <li>
          <button id="add" type="button" onClick={add}>
            Append 1,000 rows
          </button>
        </li>
        <li>
          <button id="update" type="button" onClick={update}>
            Update every 10th row
          </button>
        </li>
        <li>
          <button id="clear" type="button" onClick={clear}>
            Clear
          </button>
        </li>
        <li>
          <button id="swaprows" type="button" onClick={swap}>
            Swap rows
          </button>
        </li>
      </menu>
      <table>
        <tbody id="tbody">
          <For each={state.rows}>
            {(row) => (
              <tr class={isSelected(row.id) ? 'danger' : ''}>
                <td class="col-id">{row.id}</td>
                <td>
                  <button class="lbl" type="button" onClick={() => setSelected(row.id)}>
                    {row.label}
                  </button>
                </td>
                <td>
                  <button class="remove" type="button" onClick={() => remove(row.id)}>
                    x
                  </button>
                </td>
              </tr>
            )}
          </For>
        </tbody>
      </table>
    </>
  );
}

render(() => <Table />, document.getElementById('app') as HTMLElement);
