// frameworks/preact/apps/counter/main.tsx
import { render } from 'preact';
import { useState } from 'preact/hooks';

function Counter() {
  const [count, setCount] = useState(0);
  return (
    <>
      <button id="dec" type="button" onClick={() => setCount((c) => c - 1)}>
        -
      </button>
      <output id="count">{count}</output>
      <button id="inc" type="button" onClick={() => setCount((c) => c + 1)}>
        +
      </button>
    </>
  );
}

render(<Counter />, document.getElementById('app') as HTMLElement);

// frameworks/lit/apps/counter/main.ts
import { html, LitElement } from 'lit';

class BenchCounter extends LitElement {
  static override properties = { count: { state: true } };
  declare count: number;

  constructor() {
    super();
    this.count = 0;
  }

  override render() {
    return html`
      <button id="dec" type="button" @click=${() => this.count--}>-</button>
      <output id="count">${this.count}</output>
      <button id="inc" type="button" @click=${() => this.count++}>+</button>
    `;
  }
}
customElements.define('bench-counter', BenchCounter);
document.getElementById('app')?.append(new BenchCounter());
